module.exports = {
  someSidebar: {
    "30-seconds-of-ts": [
      "accumulate",
      "all",
      "allEqual",
      "and",
      "any",
      "aperture",
      "approximatelyEqual",
      "arrayToCSV",
      "ary",
      "attempt",
      "average",
      "averageBy",
      "bifurcate",
      "bifurcateBy",
      "binary",
      "bind",
      "binomialCoefficient",
      "both",
      "capitalize",
      "capitalizeEveryWord",
      "castArray",
      "celsiusToFahrenheit",
      "chunk",
      "colorize",
    ],
  },
};
